---
title: "Mapping with OvertureR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Mapping with OvertureR}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r eval=FALSE}
# install if needed:
install.packages("mapgl")
install.packages("overtureR")
```

```{r setup}
library(overtureR)
library(mapgl)
library(dplyr)
library(sf)
```

```{r}
bbox <- c(xmin = -73.9911, xmax = -73.9855, ymin = 40.7551, ymax = 40.7591)

broadway <- open_curtain("building", bbox, as_sf = T) |> select(height, geometry)

maplibre(bounds = broadway, pitch = 45) |>
  add_fill_extrusion_layer(
    id = "buildings", source = broadway, fill_extrusion_color = "lightgray",
    fill_extrusion_height = list("get", "height")
  )
```

Where is the opera? 

For this example, we're going to take a flight into DC to see the opera at the
Kennedy center. We're flying into Ronald Regan Airport:

```{r}
dca
```

I'd 
